### ISSUE TITLE
Make comment percentage test in CI only test against headers.

### ISSUE THREAD

**Issue by TheJhonny007** [cosmoscout/cosmoscout-vr#107]
The comment percentage should only be tested against headers. If a new method is added to a class it can be a dozen line in the cpp file, but only a single line comment is required to document its behaviour. 

I think it should only be tested against the ammount of available methods/classes.

**Comment by Schneegans** [comment]
I have to disagree. While comments in headers are useful for users of a library (in our case plugin developers), I believe that comments in source files are at least of equal importance for the developers of CosmoScout VR. Especially in the context of research software like CosmoScout VR it is very important not only to document _what_ a method does but also _how_ it does it.

And of course, if there is a PR where it's obviously not necessary to meet the target comment line percentage (for example due to large inline look-up-tables or very long enum classes) we can always ignore the failed check.

**Comment by TheJhonny007** [comment]
Yeah, I have to agree.
