### ISSUE TITLE
CURL dependency error

### ISSUE THREAD

**Issue by Xeyos88** [cosmoscout/cosmoscout-vr#176]
During the execution of the make for external dependencies the step for installing CURL fails.
Executed command:

`.\make_externals.bat -G "Visual Studio 16 2019"`

![image](https://user-images.githubusercontent.com/16436299/83881426-eaf6a680-a740-11ea-9cae-c4d45766c3c3.png)

By performing the next step, the CURL include and library variables are therefore not found. Even if you specify them manually, you cannot generate the folder with the executable.

CMAKE version 3.17.2

**Comment by TheJhonny007** [comment]
Hi, 

which version of CosmoScout are you trying to compile? Is it the latest develop branch or master?
CMake 3.17 changed the bundled FindCurl.cmake, which requires an extra CMake argument.

This is fixed in develop. If you want to fix it in master you can change your `make_externals.bat` and append `-DCURL_NO_CURL_CMAKE=On` to the curlpp section like this:

```bat
cmake %CMAKE_FLAGS% ... <other options> ... -DCURL_NO_CURL_CMAKE=On^
      "%EXTERNALS_DIR%/curlpp" || exit /b
```

Also Visual Studio 2019 requires an extra parameter to get a 64bit build:
```.bat
.\make_externals.bat -G "Visual Studio 16 2019" -A x64
```

**Comment by Xeyos88** [comment]
Hi,

I'm trying to compile the master.

I will try to insert the suggested changes.

**Comment by TheJhonny007** [comment]
Did it work? Can we close this issue?

**Comment by Xeyos88** [comment]
Yes, it works.
Thanks.
