### ISSUE TITLE
Externals fail to build in debug mode

### ISSUE THREAD

**Issue by TheFridge76** [cosmoscout/cosmoscout-vr#211]
## Describe the Bug
Multiple externals fail to build in debug mode:

Libtiff and Vista fail with messages similar to `LINK : fatal error LNK1104: Datei "freeglut.lib" kann nicht ge÷ffnet werden. [C:\cosmoscout-vr-hub\build\windows-extern
als-Debug\libtiff\tools\tiffgt.vcxproj]`.
Apparently a freeglut header file from a local strawberry perl installation is used, which always loads the release lib file of freeglut.
Maybe `-DGLUT_INCLUDE_DIR=%INSTALL_DIR%/include` should be added to the cmake command for libtiff and Vista in the make_externals.bat script to force usage of the freeglut files included with CosmoScout.

When libtiff builds successfully and if unity builds are activated, the build fails at OpenSG for multiple files with messages similar to: `C:/cosmoscout-vr-hub/externals/opensg-1.8/OSGSystem/OSGBezierCurve3D.cpp(50): error C2374: "THIS_FILE": Neudefinition;
Mehrfachinitialisierung [C:\cosmoscout-vr-hub\build\windows-externals-Debug\opensg-1.8\OSGSystem\OSGSystem.vcxproj]`.
On Windows `THIS_FILE` is defined as a static variable in multiple files, thus the build fails if those files are combined in the unity build.

1. Checkout the current `develop` branch on clean repo
2. Run make_externals.bat
3. Libtiff build fails
4. Add `-DGLUT_INCLUDE_DIR=%INSTALL_DIR%/include` to libtiff to prevent this error
5. Run again
6. OpenSG build fails

## Expected Behavior
The make_externals.bat script should run without errors.

## System
_Please complete the following information:_
 - CosmoScout VR version develop branch @6d07b2450f
 - OS: Windows 10
 - Compiler: msvc 19.16.27031.1
 - Graphics Card Intel HD Graphics 530

**Comment by JonasGilg** [comment]
Hi, thank you for the report. We will have a look at these two issues. 

For the meantime you can disable unity builds by setting the environment variable: `COSMOSCOUT_NO_UNITY_BUILD` to `true`.
See: https://github.com/cosmoscout/cosmoscout-vr/blob/develop/docs/install.md#getting-the-dependencies-1

Unity builds are a blessing and a curse at once. They reduced the build times for OpenSG by 80 - 90%, but since OpenSG is so old, they can fail randomly depending on the grouping of `.cpp` files. We already eliminated a vast majority of global definitions in OpenSG, but there are still some left.
